common:
  db_driver:  I am lihan! 3ks! (got it!!!) v0.0.0

service_api:
  aaa:
    bbbb: 333555

spring:
  datasource:
    url: jdbc:mysql://192.168.140.102:3306/bootdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

