common:
  db_driver:  I am lihan! I am a whuer! 3ks! (got it!!!)

service_api:
  aaa:
    bbbb: 333555

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bootdb?useUnicode=true&characterEncoding=utf8

