
server:
  port: 8765

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/magicLian/springcloud_demo_on_k8s.git
          search-paths: adminConfig
#          username: *************
#          password: *************
