---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  selector:
    matchLabels:
      app: springcloud-config-server

  replicas: 1

  template:
    metadata:
      labels:
        app: springcloud-config-server
    spec:
      containers:
       - name: config-server-instance
         image: registry.cn-hangzhou.aliyuncs.com/wooddeep/config-server:v0.3
         env:
         - name: EUREKA_URL
           value: eureka-server
         ports:
         - containerPort: 8765


---
kind: Service
apiVersion: v1
metadata:
  name: config-server
spec:
  selector:
    app: springcloud-config-server
  ports:
  - protocol: TCP
    port: 8765
    targetPort: 8765
  #type: NodePort


